ProcessoProduto/Models/ErrorViewModel.cs
using System;

namespace ProcessoProduto.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProcessoProduto/Models/ProdutoView.cs
using System;

namespace ProcessoProduto.Models
{
    public class ProdutoView
    {
        public int Id { get; set; }

        public string UserName { get; set; }

        public string FullName { get; set; }

        public DateTime Date { get; set; }

        public string Active { get; set; }

        public string Country { get; set; }

        public string Role { get; set; }
    }
}

ProcessoProduto/Controllers/ConsultaController.cs
using Microsoft.AspNetCore.Mvc;
using ProcessoProduto.Dominio.Dominio;
using ProcessoProduto.Models;
using ProcessoProdutoi.Negocio.Negocio;
using System.Collections.Generic;

namespace ProcessoProduto.Controllers
{
    public class ConsultaController : Controller
    {
        private ProdutoNegocio produtoNegocio;

        public ConsultaController()
        {
            produtoNegocio = new ProdutoNegocio();
        }

        public IActionResult Consultar()
        {
            return View();
        }

        public IEnumerable<Produto> ListarProduto()
        {
            List<Produto> listaProduto = new List<Produto>();

            foreach(var produto in listaProduto)
            {
                listaProduto.Add(produto);
            }

            return listaProduto;
        }

        public IActionResult Deletar(int idprodutoVM)
        {

            produtoNegocio.Deletar(idprodutoVM);
            return View("Cadastrar");
        }

        public IActionResult AtulaizarDados(ProdutoView produtoVM)
        {
            produtoVM = new ProdutoView();
            Produto produto = new Produto();
            produtoVM.UserName = produto.UserName;
            produtoVM.FullName = produto.FullName;
            produtoVM.Date = produto.Date;
            produtoVM.Country = produto.Country;
            produtoVM.Active = produto.Active;
            produtoVM.Id = produto.Id;
            produtoNegocio.Atualizar(produto);
            return View("Cadastrar");
        }
    }
}

ProcessoProduto/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ProcessoProduto.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ProcessoProduto.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProcessoProduto/Controllers/ProdutoController.cs
using Microsoft.AspNetCore.Mvc;
using ProcessoProduto.Dominio.Dominio;
using ProcessoProduto.Models;
using ProcessoProdutoi.Negocio.Negocio;

namespace ProcessoProduto.Controllers
{
    public class ProdutoController : Controller
    {
        private ProdutoNegocio produtoNegocio;

        public ProdutoController()
        {
            produtoNegocio = new ProdutoNegocio();
        }

        public IActionResult Cadastrar()
        {
            return View();
        }

        public IActionResult CadatsrarDados(ProdutoView produtoVM)
        {
            produtoVM = new ProdutoView();
            Produto produto = new Produto();
            produtoVM.Id = produto.Id;
            produtoVM.UserName = produto.UserName;
            produtoVM.FullName = produto.FullName;
            produtoVM.Date = produto.Date;
            produtoVM.Country = produto.Country;
            produtoVM.Active = produto.Active;
            produtoNegocio.AdicionarProduto(produto);
            return View("Cadastrar");
        }

       
    }
}

ProcessoProduto/Views/Consulta/Consultar.cshtml
@model List<ProcessoProduto.Models.ProdutoView>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="container-fluid">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="@Url.Action("Inicio", "Inicial")">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Cadastrar", "Cadastro")">Cadastro</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Consultar", "Consulta")">Consulta</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Pesquisar", "Pesquisa")">Pesquisa</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<hr/>
<div class="modal-dialog">
    <div class="modal-content">
              <div class="modal-header">
                <h4 class="modal-title">Consultar a passagem</h4>
            </div>
        </div> 
   </div>
   <table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">username</th>
      <th scope="col">Fullname</th>
      <th scope="col">Date</th>
       <th scope="col">Country</th>
      <th scope="col">Active</th>
    </tr>
  </thead>
  <tbody>
      @foreach(var produto in Model)
      {
             <td>{produto.Id}</td>
             <td>{produto.Fullname}</td>
             <td>{produto.Date}</td>
             <td>{produto.Country}</td>
             <td>{produto.Active}</td>
             <td id="Deletar?id">Excluir</td>
             <td id="Atuaslizar?id">Alterar</td>
      }
        </tbody>
</table>
</div>

ProcessoProduto/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ProcessoProduto/Views/Produto/Cadastrar.cshtml
@model ProcessoProduto.Models.ProdutoView
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
       ViewData["Title"] = "Cadastrar";
}
@using(Html.BeginForm())
{
        <div class="form-inline">
            <div class="form-group">
                    @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-4" })

                    <div class="col-md-10">
                        @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                    </div>
             </div>
              <div class="form-group">
                    @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-4" })

                    <div class="col-md-10">
                        @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
                    </div>
             </div>
              <div class="form-group">
                    @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-4" })

                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                    </div>
             </div>
             <div class="form-group">
                    @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-4" })

                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
                    </div>
             </div>
             <div class="form-group">
                    @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-4" })

                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Active, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                    </div>
             </div>
         </div>
         <br/>
          <button type="button" class="btn btn-primary" onclick="CadatsrarDados(produtoVM)">Salvar os Dados</button>
}

ProcessoProduto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProcessoProduto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProcessoProduto</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ProcessoProduto - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>